//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPI.Persistence.EntityRepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> NombreEtages_de { get; set; }
        public Nullable<int> NombreEtages_a { get; set; }
        public Nullable<int> Etage_de { get; set; }
        public Nullable<int> Etage_a { get; set; }
        public Nullable<decimal> Pieces_de { get; set; }
        public Nullable<decimal> Pieces_a { get; set; }
        public Nullable<decimal> Surface_de { get; set; }
        public Nullable<decimal> Surface_a { get; set; }
        public Nullable<decimal> Prix_de { get; set; }
        public Nullable<decimal> Prix_a { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Region Region { get; set; }
        public virtual TypeImmobilier TypeImmobilier { get; set; }
    }
}
