//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPI.Persistence.EntityRepositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Ventes = new HashSet<Vente>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int RegionId { get; set; }
        public string Rue { get; set; }
        public string Npa { get; set; }
        public string Localite { get; set; }
        public int Nombre_Etages { get; set; }
        public int Etage { get; set; }
        public decimal Pieces { get; set; }
        public decimal Surface { get; set; }
        public decimal Prix { get; set; }
        public int VendeurId { get; set; }
        public byte Actuel { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Region Region { get; set; }
        public virtual TypeImmobilier TypeImmobilier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vente> Ventes { get; set; }
    }
}
